Card.create name: 'Math YouTuber 3blue1brown', image: '3blue1brown.jpg'
Card.create name: 'HTTP 401', image: '401.jpg'
Card.create name: 'Berkshire Brewing Company Steel Rail Extra Pale Ale', image: 'bbc_steel_rail.png'
Card.create name: 'British comedian Bob Mortimer', image: 'bob_mortimer.jpg'
Card.create name: '0xCAFEBABE', image: 'cafebabe.png'
Card.create name: 'The Circle of Fifths', image: 'circle_of_fifths.png'
Card.create name: 'British musician Jacob Collier', image: 'jacob_collier.jpg'
Card.create name: 'Krobus from Stardew Valley', image: 'krobus.png'
Card.create name: '7-time Formula One world champion Lewis Hamilton', image: 'lewis_hamilton.jpg'
Card.create name: 'My dogs', image: 'my_dogs.jpg'
Card.create name: 'A turret from Portal', image: 'portal_turret.jpg'
Card.create name: 'Russian classical composer Sergei Rachamaninoff', image: 'rachmaninoff.jpg'
Card.create name: 'W.E.B DuBois Memorial Library at UMass', image: 'web_dubois_library.jpg'
Card.create name: 'An aardvark', image: 'aardvark.jpg'
Card.create name: 'A piano', image: 'piano.jpg'
Card.create name: 'Colored pencils', image: 'colored_pencils.jpg'
Card.create name: 'A ball of rubber bands', image: 'rubberbands.jpg'
Card.create name: 'Wagon wheels', image: 'wagonwheels.jpg'
Card.create name: 'A school of fish', image: 'schoolfish.jpg'
Card.create name: 'The steering wheel of an antique car', image: 'antiquecar.jpg'
Card.create name: 'A pair of boots sitting on a set of stairs', image: 'bootsonstairs.jpg'
Card.create name: 'A spiral staircase', name: 'spiralstaircase.jpg'
Card.create name: 'A bicycle handlebar', name: 'bicyclehandlebar.jpg'
Card.create name: 'A ring of colored pencils', name: 'ringpencils.jpg'
Card.create name: 'An isolated phone booth', name: 'phonebooth.jpg'
Card.create name: 'Someone riding a bicycle while wearing a VR headset', image: 'bicyclevr.jpg'
Card.create name: "A bird's eye view of a small island", image: 'island.jpg'
Card.create name: 'A pair of googly eyes on a small piece of moss', image: 'moss.jpg'
Card.create name: 'A bear taking a bath', image: 'bear.jpg'
Card.create name: 'Someone holding a pineapple aloft in a field', image: 'pineapple.jpg'
Card.create name: 'Tires stacked in a cross-hatch pattern', image: 'tires.jpg'
Card.create name: 'A cat examines an orange', image: 'catorange.jpg'
Card.create name: 'Several threads passing through the eye of a needle', image: 'threadsneedle.jpg'
Card.create name: 'An overly complex gutter downspout', image: 'gutter.jpg'
Card.create name: 'An image of a lost cat on a tree', image: 'lostcat.jpg'
Card.create name: 'A wooden walkway winding through some trees', image: 'walkway.jpg'
Card.create name: 'Bert from Sesame Street sitting on a fencepost', image: 'ernie.jpg'
Card.create name: 'Cave', image: 'cave.jpg'
Card.create name: "An easy game of Where's Waldo", image: 'waldo.jpg'
Card.create name: 'A birthday party for dogs', image: 'dogbirthday.jpg'